[workspace]
resolver = "2"
members = [
    "bindings/python",
    "cli",
    "rookie-rs",
    "rookie-rs/examples/chrome",
    "rookie-rs/examples/http",
    "rookie-rs/examples/logging"
]


