[package]
name = "cli"
version = "0.5.1"
edition = "2021"

[dependencies]
clap = { version = "4.4.6", features = ["derive"] }
lazy_static = "1.4.0"
pretty_env_logger = "0.5.0"
rookie = { path = "../rookie-rs" }
serde_json = "1.0.107"
